@startuml
start

:Ввод параметров героя;
:Выбор жанра;

:Формирование структуры Кэмпбелла;

:Зов к приключению;
:Отказ от пути;
:Встреча с наставником;
:Преодоление испытаний;
:Кульминация;
:Возвращение героя;

:Формирование prompt;

:Генерация через LLaMA;

if (Результат устраивает?) then (да)
  :Сохранение в БД;
else (нет)
  :Изменение параметров;
endif

stop
@enduml